sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 092100
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tFK3UAQ47fm3ppJJ1fU
    access-key-secret: a03YjSAQFdqD16QdUqboJVO8BrA84W
    bucket-name: changangqiongwaimai1
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wxcf152626eeb7c6f2
    secret: 6feb134af833e9656ec352e20e796126